# -*- coding: utf-8 -*-
"""spleeter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/deezer/spleeter/blob/master/spleeter.ipynb

# Install spleeter
"""

!apt install ffmpeg sox  lame libsox-fmt-mp3

pip install spleeter

from IPython.display import Audio

"""# Separate from command line"""

from google.colab import files
import IPython.display as ipd
import sys
files.upload()
! echo "Moving song.mp3...."
! mv song.mp3 audio_example.mp3

Audio('audio_example.mp3')

!spleeter separate -o output/ -p spleeter:4stems audio_example.mp3

!ls output/audio_example

Audio('output/audio_example/drums.wav')

Audio('output/audio_example/bass.wav')

Audio('output/audio_example/vocals.wav')

Audio('output/audio_example/other.wav')

! sox -m output/audio_example/bass.wav output/audio_example/vocals.wav output/audio_example/other.wav -C 192 merged.mp3 gain 5

!ls

Audio('merged.mp3')

files.download('merged.mp3')