name: Release Workflow

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow creating releases and uploading files

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        apt-get update && apt-get install -y curl
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Create Release Docker Image
      run: |
        docker build -t nodrums:latest .
        mkdir -p release
        docker save nodrums:latest | gzip > release/nodrums-latest.tar.gz

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/nodrums-latest.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up
      run: rm -rf release
